config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homep.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('management/', include('management.urls', namespace='management')),
    path('travels/', include('travels.urls', namespace='travels')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    
]

homep/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('add/orders/<int:travel_id>/', views.AddOrderView.as_view(), name='add_order'),
    path('orders/detail/<int:user_id>/', views.CartListView.as_view(), name='cart_list'),
    path('order/delete/', views.CartDeleteView.as_view(), name='order_delete'),
    path('ticket/detail/<int:ticket_id>/', views.TicketListUserView.as_view(), name='ticket_lsit_user'),
    path('order/pay/<int:user_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('purchased/list<int:user_id>/', views.PurchasedListView.as_view(), name='purchased_list'),
    path('purchase/delete/', views.PurchasedDeleteView.as_view(), name='purchase_delete'),
]

orders/models.py
from django.db import models
from accounts.models import User
from django.contrib.auth import get_user_model
from travels.models import Ticket
from .manager import SoftDeleteManager
from django.db.models.signals import pre_delete
from jalali_date import datetime2jalali


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order_user')
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    paid_price = models.IntegerField(null=True)
    paid_date = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False ,null=True, blank=True)
    
    # first objects - filters applied to object
    # second - all models without filter 
    objects = SoftDeleteManager()  # Custom manager for non-deleted objects
    all_objects = models.Manager()  # Default manager to access all objects, including soft-deleted ones
    
    def __str__(self) -> str:
        return f'{self.ticket.travel}'
 
    def delete(self):
        pre_delete.send(sender=self.__class__, instance=self)
        self.is_deleted = True
        self.save()
        
    @property
    def get_cost(self):
        return self.ticket.travel.price * self.quantity


    @property
    def get_total_cost_for_user(self):
        orders = Order.objects.filter(user=self.user)
        total_cost = sum(order.get_cost for order in orders)
        return total_cost
    
    @property
    def get_jalali_date(self):
        return datetime2jalali(self.created).replace(microsecond=0)
    
    
class PurchasedOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchased_user')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='purchased_order')
    created = models.DateTimeField(auto_now=True)
    
    @property
    def get_jalali_date(self):
        return datetime2jalali(self.created).replace(microsecond=0)

orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

class AddOrderForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=1)
    
    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity < 1 or quantity > 1:
            raise ValidationError('your order must be 1 item')
        return quantity

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Order, PurchasedOrder
from .forms import AddOrderForm
from accounts.models import User
from wallet.models import TransectionLog, Wallet
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from travels.models import Travel, Ticket
from management.models import BasePercent

class TicketListUserView(View):
    form_class = AddOrderForm
    def get(self, request, *args, **kwargs):
        order_form = self.form_class
        base_percent = BasePercent.objects.all().last()
        tickets = Ticket.objects.filter(id=kwargs['ticket_id'])
        ticket = tickets.get(id=kwargs['ticket_id'])
        if ticket.is_available:
            return render(request, 'orders/ticket_details_user.html', {'order_form':order_form, 'tickets':tickets, 'base_percent':base_percent})
        messages.error(request, 'This Ticket not available!', 'danger')
        return redirect('travels:ticket_detail', ticket.travel.id)
    

class AddOrderView(LoginRequiredMixin, View):
    form_class = AddOrderForm

    def post(self, request, *args, **kwargs):
        order_form = self.form_class(request.POST)
        user = get_object_or_404(User, pk=request.user.id)
        ticket = Ticket.objects.get(id=kwargs['travel_id'])
            
        if order_form.is_valid():
            cd = order_form.cleaned_data
            if cd['quantity'] > ticket.travel.quantity:
                messages.error(request, 'Your request greater than of quantity!', 'danger')
                return redirect('home:home')
                
            add_cart, crt = Order.objects.get_or_create(user=user, ticket=ticket)
            add_cart.ticket = ticket
            add_cart.quantity += cd['quantity']
            add_cart.save() 
            ticket.user = user
            ticket.is_available = False
            ticket.save()
            return redirect('orders:cart_list', user.id)
        messages.error(request, 'You Must choice 1 item', 'danger')
        return redirect('orders:ticket_lsit_user', ticket.id)
        
       
class OrderPayView(LoginRequiredMixin, View):
    def get(self, request, user_id, *args, **kwargs):
        orders = Order.objects.filter(user=user_id)
        wallet = Wallet.objects.get(user=user_id)
        
        for order in orders:
            product_price = order.get_cost
            check_credit = wallet.check_credit(product_price)
            if check_credit:
                wallet.withdraw(product_price)
                order.paid_price = product_price
                order.save()
                a = PurchasedOrder.objects.create(user_id=user_id, order=order)
                print(a)
                TransectionLog.objects.create(transection_type='2', wallet=wallet, 
                                            amount=(-product_price), log_ids=order.id)
                order.delete()
            else:
                messages.error(request, 'Your Account balance is Not insufficient!', 'danger')
                return redirect('wallet:add_amount')
        
        messages.success(request, 'Successfully paid', 'success')
        return redirect('orders:cart_list', order.user.id)
    

class CartListView(View):
    def get(self, request, user_id):
        orders = Order.objects.filter(user=user_id).order_by('-updated')
        last_item = orders.last()
        total_cost = (last_item.get_total_cost_for_user if last_item else 0)
        return render(request, 'orders/cart_list.html', {'orders':orders, 'total_cost':total_cost})


class PurchasedListView(LoginRequiredMixin, View):
    def get(self, request, user_id, *args, **kwargs):
        purchesd_list = PurchasedOrder.objects.filter(user_id=user_id)
        return render(request, 'orders/purchased_list.html', {'purchased':purchesd_list})


class PurchasedDeleteView(LoginRequiredMixin, View):
    def get(self, request):
        param = request.GET.get('purchase_id')
        if param:
            purchase = PurchasedOrder.objects.get(pk=param)
            purchase.delete()
            messages.success(request, 'Your purchase orders and money returned your wallet.', 'success')
            return redirect('orders:purchased_list', request.user.id)
        
 
class CartDeleteView(LoginRequiredMixin, View):
    def get(self, request):
        param = request.GET.get('order_id')
        if param:
            order = Order.objects.get(pk=param)
            order.delete()
            messages.success(request, 'Your order deleted.', 'success')
            return redirect('orders:cart_list', request.user.id)
        

orders/templates/orders/admin_change_driver_ticket.html
{% extends 'base.html' %}

{% block content %}
    
    <form action="" method="post">
        {% csrf_token %}
        {{ ticket_form.as_p }}
        <input type="submit" class="btn btn-success">
    </form>
    
{% endblock %}

orders/templates/orders/cart_list.html
{% extends 'base.html' %}


{% block content %}
<br>

<!-- CSS -->
<style>
  .myTable { 
    width: 100%;
    text-align: left;
    background-color: rgb(245, 243, 223);
    border-collapse: collapse; 
    }
  .myTable th { 
    background-color: rgb(248, 221, 155);
    color: rgb(49, 47, 47); 
    }
  .myTable td, 
  .myTable th { 
    padding: 10px;
    border: 1px solid rgb(218, 165, 32); 
    }

    body {
    counter-reset: section;
}

table tbody tr th::before {
    counter-increment: section;
    content: "Section " counter(section);
}

table tbody tr th::before {
    content: counter(section);
}
</style>

<h4>Your Orders:</h4> <br>

<div style="display: flex; justify-content: end; text-align: center;">
  <a href="{% url 'orders:purchased_list' request.user.id %}" class="btn btn-success" >MyOrderPurchased</a>
</div><br>

<table class="myTable">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">driver and car</th>
        <th scope="col">startcity</th>
        <th scope="col">destanition city</th>
        <th scope="col">seat_number</th>
        <th scope="col">Price per unit</th>
        <th scope="col">datetime to move</th>
        <th scope="col">Remove</th>

      </tr>
    </thead>
    <tbody>
    {% for order in orders%}
       
      <tr >
        <th scope="row"></th>
        <td>{{ order.ticket.travel.driver_car }}</td>
        <td>{{ order.ticket.travel.startcity }} </td>
        <td>{{ order.ticket.travel.destanition }}</td>
        <td>{{ order.ticket.seat_number }}</td>
        <td>{{ order.ticket.travel.price }}</td>
        <td>{{ order.ticket.travel.get_jalali_start_time }}</td>
        
        <td><a href="{% url 'orders:order_delete' %}?order_id={{ order.id }}" class="btn btn-danger">Delete</a></td>
      </tr>
    {% endfor %} 
    <tr>
      <td><h5>Total_cost: {{total_cost}}.Toman</h5></td>
    </tr>
    </tbody>
   
</table><br>
  {% if total_cost > 0 %}
  <a href="{% url 'orders:order_pay' request.user.id %}" class="btn btn-success col-md-1">Pay</a> 
  {% else %}
    <h6>0</h6>
  {% endif %}
{% endblock %}

orders/templates/orders/orders_detail.html
{% extends 'base.html' %}


{% block content %}
<br>

<!-- CSS -->
<style>
  .myTable { 
    width: 100%;
    text-align: left;
    background-color: rgb(245, 243, 223);
    border-collapse: collapse; 
    }
  .myTable th { 
    background-color: rgb(248, 221, 155);
    color: rgb(49, 47, 47); 
    }
  .myTable td, 
  .myTable th { 
    padding: 10px;
    border: 1px solid rgb(218, 165, 32); 
    }

    body {
    counter-reset: section;
}

table tbody tr th::before {
    counter-increment: section;
    content: "Section " counter(section);
}

table tbody tr th::before {
    content: counter(section);
}
</style>

<h4>Your Orders:</h4> <br>
<table class="myTable">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">driver and car</th>
        <th scope="col">startcity</th>
        <th scope="col">destanition city</th>
        <th scope="col">Price per unit</th>
        <th scope="col">datetime to move</th>
        <th scope="col">quantity</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>

      </tr>
    </thead>
    <tbody>
    {% for order in orders%}
       
      <tr >
        <th scope="row"></th>
        <td>{{ order.ticket.travel.driver_car }}</td>
        <td>{{ order.ticket.travel.startcity }} </td>
        <td>{{ order.ticket.travel.destanition }}</td>
        <td>{{ order.ticket.travel.price }}</td>
        <td>{{ order.ticket.travel.date_time.time }}---({{ order.ticket.travel.date_time.date|date:"D-d-m-Y" }})</td>
        <td>{{ order.get_cost }}</td>
        <td>{{ order.quantity }}</td>
        <td><a href="{% url 'orders:order_delete' %}?order_id={{ order.id }}" class="btn btn-danger">Delete</a></td>
      </tr>
      {% if forloop.last %}  
      <td><h5>Total cost:{{ order.get_total_cost_for_user }}</h5></td>
      {% endif %}
    {% endfor %} 

    </tbody>
</table>
{% endblock %}

orders/templates/orders/purchased_list.html
{% extends 'base.html'%}


{% block content %}
<!-- CSS -->
<style>
    .myTable { 
      width: 100%;
      text-align: left;
      background-color: rgb(245, 243, 223);
      border-collapse: collapse; 
      }
    .myTable th { 
      background-color: rgb(248, 221, 155);
      color: rgb(49, 47, 47); 
      }
    .myTable td, 
    .myTable th { 
      padding: 10px;
      border: 1px solid rgb(218, 165, 32); 
      }
  
      body {
      counter-reset: section;
  }
  
  table tbody tr th::before {
      counter-increment: section;
      content: "Section " counter(section);
  }
  
  table tbody tr th::before {
      content: counter(section);
  }
  </style>
  
<h4>purchased_list:</h4><br>

  <table class="myTable">
      <thead>
        <tr>
          <th>#</th>
          <th scope="col">driver and car</th>
          <th scope="col">startcity</th>
          <th scope="col">destanition city</th>
          <th scope="col">seat_number</th>
          <th scope="col">Price per unit</th>
          <th scope="col">datetime to move</th>
          <th scope="col">Remove</th>
  
        </tr>
      </thead>
      <tbody>
        {% for purchase in purchased %}
  
        <tr>
          <th scope="row"></th>
          <td>{{ purchase.order.ticket.travel.driver_car }}</td>
          <td>{{ purchase.order.ticket.travel.startcity }} </td>
          <td>{{ purchase.order.ticket.travel.destanition }}</td>
          <td>{{ purchase.order.ticket.seat_number }}</td>
          <td>{{ purchase.order.paid_price }}.Toman</td>
          <td>{{ purchase.order.ticket.travel.get_jalali_start_time }}</td>

          <td><a href="{% url 'orders:purchase_delete' %}?purchase_id={{ purchase.id }}" class="btn btn-danger">Delete</a></td>
        </tr>
        
        {% endfor %}
      </tbody>
  </table>
{% endblock %}
  

orders/templates/orders/ticket_details_user.html
{% extends 'base.html' %}

{% block content %}
    <h4>Ticket Information</h4> <br>
    <style>
        .myTable { 
          width: 100%;
          text-align: left;
          background-color: rgb(245, 243, 223);
          border-collapse: collapse; 
          }
        .myTable th { 
          background-color: rgb(248, 221, 155);
          color: rgb(49, 47, 47); 
          }
        .myTable td, 
        .myTable th { 
          padding: 10px;
          border: 1px solid rgb(218, 165, 32); 
          }
      
          body {
          counter-reset: section;
      }
      
      table tbody tr th::before {
          counter-increment: section;
          content: "Section " counter(section);
      }
      
      table tbody tr th::before {
          content: counter(section);
      }
    </style>
    
<table class="myTable">
    <thead>
        <tr>
            <th>#</th>
            <th scope="col">Startcity</th>
            <th scope="col">Destination City</th>
            <th scope="col">seat_number</th>
            <th scope="col">Time</th>
            <th scope="col">Date</th>
            <th scope="col">DriverCar</th>
            <th scope="col">capacity</th>
            <th scope="col">Price</th>
            <th scope="col">Availe</th>
            <th scope="col">ramind capacity</th>
        </tr>
    </thead>
    <tbody>

    {% for ticket in tickets %}
        <tr>
          <th scope="row"></th>

        <td>{{ ticket.travel.startcity }}</td> 
        <td>{{ ticket.travel.destanition }}</td>
        <td>{{ ticket.seat_number }}</td>
        <td>{{ ticket.travel.get_jalali_start_time.time }}</td>
        <td>{{ticket.travel.get_jalali_start_time.date }}</td>
        <td>{{ ticket.travel.driver_car }}</td>
        <td>{{ ticket.travel.quantity }} </td>
        <td>{{ ticket.travel.price }}.toman</td>
        <td>{{ ticket.is_available }}</td>
        <td>{{ ticket.travel.get_capacity }}</td>
    </tr>
    </tbody>
</table> <br>
        {% if ticket.is_available %}
            <form action="{% url 'orders:add_order' ticket.id %}" method="post" novalidate>
                {% csrf_token %}
                {{ order_form }} <br>
                <input type="submit" value="add to cart" class="btn btn-success col-md-1">
            </form>
        {% else %}
            <h4>This Ticket has Ended.</h4>
        {% endif %}
    {% endfor %}

<h6 style="display: flex; justify-content: end; align-items: center;">شرایط استرداد: در صورت استرداد بعد از یکساعت {{base_percent}}درصد از مبلغ بلیط کسرخواهد شد</h6>
{% endblock %}



  
       
   
  
  