config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homep.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('management/', include('management.urls', namespace='management')),
    path('travels/', include('travels.urls', namespace='travels')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    
]

homep/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

management/urls.py
from django.urls import path
from . import views

app_name = 'app_name'
urlpatterns = [
    path('admin/panel', views.AdminPanelView.as_view(), name='admin_panel'),
    path('admin/change/city', views.ChangeCityView.as_view(), name='change_city'),
    path('list_city/', views.ListCityView.as_view(), name='list_city'),
    path('driver/detail/', views.DriverDetailView.as_view(), name='driver_detail'),
    path('driver/panel', views.DriverRegisterAdminView.as_view(), name='driver_register_admin'),
    path('base/time/', views.BaseTimeView.as_view(), name='base_time'),
    path('base/price/', views.BasePriceView.as_view(), name='base_price'),
    path('price/list/', views.BasePriceList.as_view(), name='price_list'),
    path('car/register/', views.CarRegisterView.as_view(), name='car_register'),
    path('car/list/', views.CarListView.as_view(), name='car_list'),
    path('delete/city/', views.DeleteCityView.as_view(), name='delete_city'),
    path('driver/delete/', views.DeleteDriverView.as_view(), name='driver_delete'),
    path('submit/basepercent/', views.BasePercentView.as_view(), name='base_percent'),
    path('base/refund/', views.BaseTimeRefundView.as_view(), name='base_time_refund'),
    path('base/time/refund/list', views.BaseTimeRefundList.as_view(), name='base_time_refund_list'),
    path('base/percent/list/', views.BasePercentListView.as_view(), name='base_percent_list'),
    
    
]

travels/urls.py
from django.urls import path
from . import views


app_name = 'travels'
urlpatterns = [
    path('admin/travels/', views.TravelRegisterView.as_view(), name='travel_admin'),
    path('delete/travel', views. DeleteTravelView.as_view(), name='delete_travel'),
    path('approve/travel/<int:travel_id>/', views.ApproveTravelAdminView.as_view(), name='approve_travel'),
    path('register/travel/<int:driver_id>/', views.DriverRegisterTravel.as_view(), name='driver_register_travel'),
    path('travel/details/', views.TravelListView.as_view(), name='travel_detail'),
    path('ticket/detail/<int:travel_id>/', views.TicketListAdminView.as_view(), name='ticket_list'),
    path('travel/list/ticket/', views.TravelListTicketView.as_view(), name='travel_list_admin'),
    path('ticket/info/<int:travel_id>/', views.TravelDetailUserView.as_view(), name='ticket_detail'),
    
]

wallet/urls.py
from django.urls import path
from . import views

app_name = 'wallet'
urlpatterns = [
    path('wallet/add/amount/', views.AddAmountWalletView.as_view(), name='add_amount'),
    path('transection/list/', views.TransecitonListView.as_view(), name='transection_list'),
    path('transection/request/<int:transection_id>/', views.TransectionRequestListView.as_view(), name='transection_request'),
    path('user/transection/<int:user_id>/', views.TransectionLogListView.as_view(), name='user_transection'),
    path('wallet/balance/', views.WalletBalanceListView.as_view(), name='wallet_balance'),
    
]

management/models.py
from django.db import models
from accounts.models import Driver
from jalali_date import datetime2jalali, date2jalali


class Car(models.Model):
    name = models.CharField(max_length=50)
    capacity = models.IntegerField()
   
    def __str__(self):
       return f'{self.name}'
   
    
class DriverCar(models.Model):
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    car_production_date = models.DateField()
    
    def __str__(self):
        return f'{self.driver}-{self.car}'
    
    @property
    def get_jalali_date(self):
        return date2jalali(self.car_production_date)
    

class City(models.Model):
    name = models.CharField(max_length=100)
    lat = models.FloatField()
    lon = models.FloatField()

    class Meta:
        verbose_name = 'city'
        verbose_name_plural = 'cities'

    def __str__(self):
        return self.name
    

class BasePrice(models.Model):
    price_per_km = models.IntegerField()
    created = models.DateTimeField(auto_now=True)
    
    @property
    def get_jalali_date(self):
        return datetime2jalali(self.created).replace(microsecond=0)
    
class BaseTime(models.Model):
    base_time = models.IntegerField()
 
    
class BasePercent(models.Model):
    base_percent = models.IntegerField()
    created = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.base_percent)
    
    @property
    def get_jalali_date(self):
        return date2jalali(self.created)
    
class BaseTimeRefund(models.Model):
    base_time = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now=True)
    
    @property
    def get_jalali_date(self):
        return datetime2jalali(self.created).replace(microsecond=0)

management/forms.py
from django import forms
from .models import City, Car
from accounts.models import User
from django.core.exceptions import ValidationError


class CityForm(forms.Form):
    city = forms.CharField(max_length=30)
    lat = forms.FloatField()
    lon = forms.FloatField()
    
    def clean_city(self):
        city = self.cleaned_data['city']
        city_model = City.objects.filter(name=city).exists()
        if city_model:
            raise ValidationError('This City Exists.', 'error')
        return city

        
class DriverRegisterForm(forms.Form):
    car = forms.ModelChoiceField(queryset=Car.objects.all())
    car_production_date = forms.DateField()
         

class CarRegisterForm(forms.Form):
    name = forms.CharField(max_length=20)
    capacity = forms.IntegerField(max_value=40) 
 
    
class CityChoiceForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ('name',)
    
    
class DriverUser(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.all())
    

class BaseTimeForm(forms.Form):
    base_time = forms.IntegerField()
  
    
class BasePriceForm(forms.Form):
    price_per_km = forms.IntegerField()


class BasePercentForm(forms.Form):
    base_percent = forms.IntegerField()  


class BaseTimeRefundForm(forms.Form):
    base_time_refund = forms.IntegerField()

management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from utils import IsAdmin
from .forms import (
    CityForm, 
    BasePriceForm, 
    BaseTimeForm, 
    CarRegisterForm, 
    DriverUser, 
    DriverRegisterForm, 
    BasePercentForm, 
    BaseTimeRefundForm,
)
from .models import City, DriverCar, Driver, Car, BaseTime, BasePrice, BasePercent, BaseTimeRefund
from travels.models import Travel
from django.contrib import messages


class AdminPanelView(View):
    def get(self, request):
        return render(request, 'management/admin_panel.html')
        
        
class ChangeCityView(IsAdmin, View):
    class_form = CityForm
    def get(self, request):
            city_form = self.class_form
            return render(request, 'management/admin_change_city.html', {'city_form':city_form})
      
    def post(self, request):
            city_form = self.class_form(request.POST)
            if city_form.is_valid():
                cd = city_form.cleaned_data
                City.objects.create(name=cd['city'], lat=cd['lat'], lon=cd['lon'])
                messages.success(request, 'City Submitted Successfully.')
                return redirect('management:list_city')
            return render(request, 'management/admin_change_city.html', {'city_form':city_form})

 
class ListCityView(IsAdmin, View):
    def get(self, request):
        cities = City.objects.all()
        return render(request, 'management/city_list.html', {'cities':cities})
        

class DriverRegisterAdminView(IsAdmin, View):
    driver_register_form = DriverRegisterForm
    user_select = DriverUser
    def get(self, request):
            form = self.driver_register_form
            user_select = self.user_select
            return render(request, 'management/admin_r_d.html', {'form':form, 'user_select':user_select})
    
    def post(self, request):
            form = self.driver_register_form(request.POST)
            user_select = self.user_select(request.POST)
            
            if form.is_valid() and user_select.is_valid():
                cd = form.cleaned_data
                driver = Driver.objects.create(user=user_select.cleaned_data['user'])
                messages.success(request, 'User Registered as a Driver.')
                DriverCar.objects.create(driver=driver, car=cd['car'], car_production_date=cd['car_production_date'])
                return redirect('management:driver_detail')
            return render(request, 'management/admin_r_d.html', {'form':form, 'user_select':user_select})
        
        
class DriverDetailView(IsAdmin, View):
    def get(self, request):
            drivers = DriverCar.objects.all()
            return render(request, 'management/driver_list.html', {'drivers':drivers})


class CarRegisterView(IsAdmin, View):
    class_form = CarRegisterForm
    def get(self, request):
        car_form = self.class_form
        return render(request, 'management/car_register.html', {'car_form':car_form})

    def post(self, request):
        car_form = self.class_form(request.POST)
        if car_form.is_valid():
            cd = car_form.cleaned_data
            Car.objects.create(name=cd['name'], capacity=cd['capacity'])
            messages.success(request, 'Car Registered.', 'success')
            return redirect('management:car_list')
        return render(request, 'management/car_register.html', {'car_form':car_form})


class CarListView(IsAdmin, View):
    def get(self, request):
        cars = Car.objects.all()
        return render(request, 'management/car_list.html', {'cars':cars})


class BasePriceList(IsAdmin, View):
    def get(self, request):
        prices = BasePrice.objects.all().order_by('-created')
        return render(request, 'management/price_list.html', {'prices':prices})
    

class BasePriceView(IsAdmin, View):
    class_from = BasePriceForm
    def get(self, request):
        price_form = self.class_from
        return render(request, 'management/base_price.html', {'price_form':price_form})
    def post(self, request):
        price_form = self.class_from(request.POST)
        if price_form.is_valid():
            cd = price_form.cleaned_data
            BasePrice.objects.create(price_per_km=cd['price_per_km'])
            messages.success(request, 'baseprice created.', 'success')
            return redirect('management:price_list')
        return render(request, 'management/base_price.html', {'price_form':price_form})


class BaseTimeView(IsAdmin, View):
    form_class = BaseTimeForm
    def get(self, request):
        base_time_form = self.form_class
        return render(request, 'management/base_time_form.html', {'base_time_form':base_time_form})
    
    def post(self, request):
        base_time_form = self.form_class(request.POST)
        if base_time_form.is_valid():
            cd = base_time_form.cleaned_data
            BaseTime.objects.create(base_time=cd['base_time'])
            messages.success(request, 'basetime created.', 'success')
        return render(request, 'management/base_time_form.html', {'base_time_form':base_time_form})


class BasePercentView(IsAdmin, View):
    class_form = BasePercentForm
    def get(self, request):
        percent_form = self.class_form
        return render(request, 'management/base_percent_form.html', {'percent_form':percent_form})
    
    def post(self, request):
        percent_form = self.class_form(request.POST)
        if percent_form.is_valid():
            cd = percent_form.cleaned_data
            BasePercent.objects.create(base_percent=cd['base_percent'])
            messages.success(request, 'base percent successfully!', 'success')
            return redirect('management:admin_panel')
        return render(request, 'management/base_percent_form.html', {'percent_form':percent_form})
 
 
class BasePercentListView(IsAdmin, View):
    def get(self, request):
        percent_list = BasePercent.objects.all().order_by('-created')
        return render(request, 'management/base_percent_list.html', {'percent_list':percent_list})

        
class DeleteCityView(IsAdmin, View):
    def get(self, request):
        city_ids = request.GET.get('city_ids')
        try:
            city_ids = city_ids.split(",")
        except:
            city_ids = []
        if city_ids:
            City.objects.filter(id__in=city_ids).delete()
            messages.success(request, 'City deleted')
            return redirect('management:list_city')
        
        
class DeleteDriverView(IsAdmin, View):
    def get(self, request):
        driver_ids = request.GET.get('driver_id')
        try:
            driver_ids = driver_ids.split(',')
        except:
            driver_ids = []
        if driver_ids:
            Driver.objects.filter(id__in=driver_ids).delete()
            messages.success(request, 'Driver deleted')
            return redirect('management:driver_detail')
     
        
class BaseTimeRefundView(IsAdmin, View):
    form_class = BaseTimeRefundForm
    def get(self, request):
        form = self.form_class
        return render(request, 'management/base_time_refund.html', {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            BaseTimeRefund.objects.create(base_time=cd['base_time_refund'])   
            messages.success(request, 'Base Time for deduction of refund.', 'success') 
            return redirect('management:base_time_refund_list')   
        messages.error(request, 'You must complete this form', 'danger')
        return render(request, 'management/base_time_refund.html', {'form':form})
   
    
class BaseTimeRefundList(IsAdmin, View):
    def get(self, request):
        time_refund = BaseTimeRefund.objects.all().order_by('-created')
        return render(request, 'management/base_time_refund_list.html', {'time_refund':time_refund})

management/templates/management/admin_change_city.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" style="color: white;">
    {% csrf_token %}
    {{ city_form.as_p }}
    <input type="submit" class="btn btn-success">
    </form>
{% endblock %}

management/templates/management/admin_panel.html
{% extends 'base.html' %}

{% block content %}
    <h4>Admin Panel</h4><br>
<div style="display: flex; gap: 16px; flex-wrap: wrap;">     

    <a href="{% url 'management:list_city' %}" class="btn btn-warning col-md-1">cities</a> 
    <a href="{% url 'management:car_list' %}" class="btn btn-warning col-md-1">Cars</a> <br>

    <a href="{% url 'management:driver_detail' %}" class="btn btn-warning col-md-1">Drivers</a>  
    <a href="{% url 'travels:travel_detail' %}" class="btn btn-warning col-md-1">Travels</a>

    <a href="{% url 'travels:travel_list_admin' %}" class="btn btn-warning col-md-1">Tickets</a> <br> <br>
    <a href="{% url 'management:base_time' %}" class="btn btn-warning col-md-1">Base Time</a> 

    <a href="{% url 'management:price_list' %}" class="btn btn-warning col-md-1">Base Price</a><br> <br>
    <a href="{% url 'wallet:transection_list' %}" class="btn btn-warning col-md-1">Transection list</a>
    
    <a href="{% url 'management:base_percent_list' %}" class="btn btn-warning col-md-1">Base Percent</a>
    <a href="{% url 'management:base_time_refund_list' %}" class="btn btn-warning col-md-1.5">BaseTimeRefund</a>

</div>
{% endblock %}

management/templates/management/admin_r_d.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        {{ user_select }} <br>
        <input type="submit" value="Register" class="btn btn-success">
    </form>
  
{% endblock %}

management/templates/management/base_percent_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ percent_form.as_p }} 
        <input type="submit" class="btn btn-success">
    </form>
{% endblock %}

management/templates/management/base_percent_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<a href="{% url 'management:base_percent' %}" class="btn btn-success">Add New Percent</a> <br><br>

<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Base Percent</th>
        <th scope="col">date</th>
      
      </tr>
    </thead>
    <tbody>
    {% for item in percent_list %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>%{{ item.base_percent }}</td>
        <td>{{ item.get_jalali_date }}</td>
      </tr>
      {% endfor %}

    </tbody>
</table>   
{% endblock %}

management/templates/management/base_price.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ price_form }} <br>
        <input type="submit" class="btn btn-success">
    </form>
{% endblock %}

management/templates/management/base_time_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ base_time_form }} <br>
        <input type="submit" class="btn btn-success">
    </form>
{% endblock %}

management/templates/management/base_time_refund.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post"  novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success">
    </form>
{% endblock %}

management/templates/management/base_time_refund_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<a href="{% url 'management:base_time_refund' %}" class="btn btn-success">Add New Time Refund</a> <br><br>

<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Base Time</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
    {% for item in time_refund %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.base_time }}</td>
        <td>{{ item.get_jalali_date }}</td>
      </tr>
      {% endfor %}

    </tbody>
</table>   
{% endblock %}

management/templates/management/car_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Car</th>
        <th scope="col">Capacity</th>
  
      </tr>
    </thead>
    <tbody>
        {% for car in cars %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ car.name }}</td>
        <td>{{ car.capacity }}</td>
       {% endfor %}
    </tbody>
</table>   
<a href="{% url 'management:car_register' %}" class="btn btn-primary">Car Register</a>

{% endblock %}

management/templates/management/car_register.html
{% extends 'base.html' %}


{% block content %}
    <h4>car register</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ car_form.as_p }}
        <input type="submit" class="btn btn-success">
    </form>
{% endblock %}

management/templates/management/city_list.html
{% extends 'base.html' %}

{% block content %}
    
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Name</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
   
        {% for city in cities %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ city.name }}</td>
      <td><a href="{% url 'management:delete_city' %}?city_ids={{ city.id }}" class="btn btn-danger">Remove</a></td>
      </tr>
      {% endfor %}
   
    </tbody>
</table>
    <br>
    <a href="{% url 'management:change_city' %}" class="btn btn-info col-md-1">Register City</a>
    
{% endblock %}

management/templates/management/driver_list.html
{% extends 'base.html' %}

{% block content %}
    
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Name</th>
        <th scope="col">Car</th>
        <th scope="col">capacity</th>
        <th scope="col">Productions-date</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
   
        {% for driver in drivers %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ driver.driver }}</td>
        <td>{{ driver.car }}</td>
        <td>{{ driver.car.capacity }}</td>
        <td>{{ driver.get_jalali_date }}</td>
        <td><a href="{% url 'management:driver_delete' %}?driver_id={{ driver.id }}">Remove</a></td>
      </tr>
      {% endfor %}
   
    </tbody>
</table>
    <br>
  <a href="{% url 'management:driver_register_admin' %}" class="btn btn-info col-md-1">Driver Register</a>
{% endblock %}

management/templates/management/price_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'management:base_price' %}" class="btn btn-info col-md-1">Register Base Price</a><br> <br>

<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">base price</th>
        <th scope="col">date</th>
      </tr>
    </thead>
    <tbody>
    {% for price in prices %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ price.price_per_km }}</td>
        <td>{{ price.get_jalali_date }}</td>
      </tr>
      {% endfor %}

    </tbody>
</table>   
    

{% endblock %}