config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homep.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('management/', include('management.urls', namespace='management')),
    path('travels/', include('travels.urls', namespace='travels')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    
]

homep/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('add/orders/<int:travel_id>/', views.AddOrderView.as_view(), name='add_order'),
    path('orders/detail/<int:user_id>/', views.CartListView.as_view(), name='cart_list'),
    path('order/delete/', views.CartDeleteView.as_view(), name='order_delete'),
    path('ticket/detail/<int:ticket_id>/', views.TicketListUserView.as_view(), name='ticket_lsit_user'),
    path('order/pay/<int:user_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('purchased/list<int:user_id>/', views.PurchasedListView.as_view(), name='purchased_list'),
    path('purchase/delete/', views.PurchasedDeleteView.as_view(), name='purchase_delete'),
]

travels/urls.py
from django.urls import path
from . import views


app_name = 'travels'
urlpatterns = [
    path('admin/travels/', views.TravelRegisterView.as_view(), name='travel_admin'),
    path('delete/travel', views. DeleteTravelView.as_view(), name='delete_travel'),
    path('approve/travel/<int:travel_id>/', views.ApproveTravelAdminView.as_view(), name='approve_travel'),
    path('register/travel/<int:driver_id>/', views.DriverRegisterTravel.as_view(), name='driver_register_travel'),
    path('travel/details/', views.TravelListView.as_view(), name='travel_detail'),
    path('ticket/detail/<int:travel_id>/', views.TicketListAdminView.as_view(), name='ticket_list'),
    path('travel/list/ticket/', views.TravelListTicketView.as_view(), name='travel_list_admin'),
    path('ticket/info/<int:travel_id>/', views.TravelDetailUserView.as_view(), name='ticket_detail'),
    
]

travels/models.py
from django.db import models
import haversine as hs
from haversine import Unit
from datetime import timedelta
from management.models import DriverCar, City, BasePrice, BaseTime
from accounts.models import User
from jalali_date import datetime2jalali


class Travel(models.Model):
    driver_car = models.ForeignKey(DriverCar, on_delete=models.CASCADE, related_name='driver_car')
    startcity = models.ForeignKey(City, on_delete=models.CASCADE, related_name='s_travel')
    destanition = models.ForeignKey(City, on_delete=models.CASCADE, related_name='d_travel')
    price = models.IntegerField(null=True, blank=True)
    date_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True, blank=True)
    approved = models.BooleanField(default=False) 
    quantity = models.IntegerField(null=True)
    
    class Meta:
        ordering = ('-date_time',)
    
    def __str__(self):
        return f'{self.startcity}-{self.destanition}'

    @property
    def get_distance(self):
        city_1 = self.startcity
        city_2 = self.destanition
        if not (city_1 or city_2):
            return 0
        loc1 = (city_1.lat, city_1.lon)
        loc2 = (city_2.lat, city_2.lon)
        result = hs.haversine(loc1,loc2, unit=Unit.KILOMETERS)
        return int(result)
    
    @property
    def get_cost(self):
        base_price = BasePrice.objects.all().last()
        return base_price.price_per_km * self.get_distance
    
    @property
    def get_time(self):
        base_t = BaseTime.objects.all().last()
        time = base_t.base_time * self.get_distance
        time_remain = self.date_time + timedelta(seconds=time)
        return time_remain
    
    @property
    def get_capacity(self):
        try:
            user = Ticket.objects.filter(travel=self, user__isnull=False).count()
            count_quantity = self.quantity - user
            return count_quantity
        except:
            return self.quantity
        
    @property
    def get_jalali_start_time(self):
        return datetime2jalali(self.date_time)
    
    @property
    def get_jalali_end_time(self):
        return datetime2jalali(self.end_time)    
    
    
class Ticket(models.Model):
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE, related_name='travel_ticket')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='user_ticket')
    is_available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    seat_number = models.PositiveIntegerField(null=True)
    
    def __str__(self):
        return f'{self.travel}'
    

travels/forms.py
from django import forms
from management.models import City, DriverCar
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget


class TravelForm(forms.Form):
    driver_car = forms.ModelChoiceField(queryset=DriverCar.objects.all())
    startcity = forms.ModelChoiceField(queryset=City.objects.all())
    destanition = forms.ModelChoiceField(queryset=City.objects.all())
    time = forms.TimeField()
    date = JalaliDateField(widget=AdminJalaliDateWidget)


class TravelRegisterDriverForm(forms.Form):
    startcity = forms.ModelChoiceField(queryset=City.objects.all())
    destanition = forms.ModelChoiceField(queryset=City.objects.all())
    time = forms.TimeField()
    date = JalaliDateField(widget=AdminJalaliDateWidget)

travels/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from management.models import DriverCar
from travels.models import Travel, Ticket
from django.contrib import messages
from utils import IsAdmin
from .forms import TravelForm, TravelRegisterDriverForm
import datetime

class TravelDetailUserView(View):
    """ ticket detail show for normal user"""   
    def get(self, request, *args, **kwargs):
        tickets = Ticket.objects.filter(travel_id=kwargs['travel_id'])
        return render(request, 'travels/ticket_list_user.html', {'tickets':tickets})
    
 
class DriverRegisterTravel(LoginRequiredMixin, View):
    travel_form = TravelRegisterDriverForm
    def get(self, request, *args, **kwargs):
        if request.user.user_type == '2':
            travel_form = self.travel_form
            return render(request, 'travels/driver_register_travel.html', {'travel_form':travel_form})
                 
    def post(self, request, *args, **kwargs):
        if request.user.user_type == '2':
            travel_form = self.travel_form(request.POST)
            if travel_form.is_valid():
                cd = travel_form.cleaned_data         
                time = cd['time']
                date = cd ['date']
                date_time = datetime.datetime.combine(date, time)   
                driver = DriverCar.objects.get(driver__user_id=request.user.id)
                travel = Travel(driver_car=driver, startcity=cd['startcity'],
                                      destanition=cd['destanition'], date_time=date_time)
                if travel.get_distance != 0:
                    travel.end_time = travel.get_time
                    travel.price = travel.get_cost
                    travel.quantity = travel.driver_car.car.capacity
                    is_travel_exists = Travel.objects.filter(driver_car=travel.driver_car, 
                                                            date_time__range=[travel.date_time, travel.end_time ]).exists()
                    if is_travel_exists:
                        messages.error(request, 'driver this time is on travel.', 'danger')
                        return render(request, 'travels/raise_error_trip_driver.html', {'travel':travel})
                    travel.save()
                    messages.success(request, 'Please Wait admin to accept Your`s travel', 'warning')
                    return redirect('accounts:driver_travel', driver.id)
                
                messages.error(request, 'startcity and destination can`t the same!', 'danger')
                return render(request, 'travels/driver_register_travel.html', {'travel_form':travel_form})
                
            messages.error(request, 'you must complete this form!', 'danger')
            return render(request, 'travels/driver_register_travel.html', {'travel_form':travel_form})
        messages.error(request, 'You don`t access this page.', 'danger')
        return redirect('home:home')


class ApproveTravelAdminView(IsAdmin, View):
    def get(self, request, travel_id):
        travel = get_object_or_404(Travel, id=travel_id)
        travel.approved = True
        travel.save()
        messages.success(request, 'Travel Approved and ticket submitted.', 'success')
        return redirect('travels:travel_detail')
    
                    
class TravelRegisterView(IsAdmin, View):
    travel_form_class = TravelForm
    def get(self, request):
            travel_form = self.travel_form_class
            return render(request, 'travels/travel_admin_register.html', {'travel_form':travel_form})

    def post(self, request):
        travel_form = self.travel_form_class(request.POST)
        
        if travel_form.is_valid():
            cd = travel_form.cleaned_data
            time = cd['time']
            date = cd ['date']
            date_time = datetime.datetime.combine(date, time)
            travel = Travel(driver_car=cd['driver_car'], startcity=cd['startcity'],
                                      destanition=cd['destanition'], date_time=date_time)
            if travel.get_distance != 0:
                travel.end_time = travel.get_time
                travel.price = travel.get_cost
                travel.quantity = travel.driver_car.car.capacity
                is_travel_exists = Travel.objects.filter(driver_car=travel.driver_car, 
                                                            date_time__range=[travel.date_time, travel.end_time ]).exists()
                print(Travel.objects.filter(driver_car=travel.driver_car, 
                                                            date_time__range=[travel.date_time, travel.end_time ]))
                if is_travel_exists:
                    messages.error(request, 'driver this time is on travel.', 'danger')
                    return render(request, 'travels/raise_error_trip_driver.html', {'travel':travel})
                travel.approved = True
                travel.save()
                messages.success(request, 'New Travel And Ticket Created', 'success')
                return redirect('travels:travel_detail')
            messages.error(request, 'startcity and destination can`t the same!!', 'danger')
            return render(request, 'travels/travel_admin_register.html', {'travel_form':travel_form})
        
        messages.error(request, 'you must complete this form!', 'danger')
        return render(request, 'travels/travel_admin_register.html', {'travel_form':travel_form})
        
        
class TicketListAdminView(IsAdmin, View):
    def get(self, request, travel_id,*args, **kwargs):
        tickets = Ticket.objects.filter(travel_id=travel_id) 
        return render(request, 'travels/ticket_list_admin_panel.html', {'tickets':tickets})


class TravelListTicketView(IsAdmin, View):
    def get(self, request):
        travels = Travel.objects.all().reverse()
        return render(request, 'travels/travel_list_to_ticket.html', {'travels':travels})        
    
class TravelListView(IsAdmin, View):
    def get(self, request):
        travels = Travel.objects.all().reverse()
        return render(request, 'travels/travel_list_admin.html', {'travels':travels})
               

class DeleteTravelView(IsAdmin, View):                
    def get(self, request):
        travel_ids = request.GET.get('travel_id')
        
        try:
            travel_ids = travel_ids.split(",")
        except:
            travel_ids = []
        if travel_ids:
            Travel.objects.filter(id__in=travel_ids).delete()
            messages.success(request, 'Travel deleted')
            return redirect('travels:travel_detail') 
 
 
 
 

travels/templates/travels/driver_register_travel.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}


{% block content %}
<h4> Travel register from driver</h4>
<div style="display: flex; margin-left: 200px;">
    <form action="" method="post">
        {% csrf_token %}
        {{ travel_form.as_p }} <br>
        <input type="submit" class="btn btn-success">
    </form>

    <!-- By default, Datepicker using jQuery, you need to set your script after loading jQuery! -->
	<!-- loading directly -->
		<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
		<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
	<!-- OR -->
	<!-- loading by form (if used AdminJalaliDateWidget) -->
		{{ form.media }}
</div>
{% endblock %}

travels/templates/travels/raise_error_trip_driver.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Driver_Car</th>
        <th scope="col">startcity</th>
        <th scope="col">destanition city</th>
        <th scope="col">distance</th>
        <th scope="col">start-time</th>
        <th scope="col">end-time</th>
        <th scope="col">date</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ travel.driver_car }}</td>
        <td>{{ travel.startcity }}</td>
        <td>{{ travel.destanition }}</td>
        <td>{{ travel.get_distance }}.Km</td>
        <td>{{ travel.date_time.time }}</td>

        <td>{{ travel.end_time.time }} Date: {{ travel.end_time.date|date:"D-d-m-Y" }}</td>

        <td>{{ travel.date_time.date }}</td>
    </tbody>
</table>   
{% endblock %}

travels/templates/travels/ticket_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">capacity</th>
    </tr>
    <tbody>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </thead>

</table>

    
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Username</th>
        <th scope="col">travel</th>
        
      </tr>
    </thead>
    <tbody>
        {% for ticket in tickets %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ ticket.user }}</td>
        <td>{{ ticket.travel }}</td>
        
      </tr>
        {% endfor %}
    </tbody>
</table>
    <br>
{% endblock %}

travels/templates/travels/ticket_list_admin_panel.html
{% extends 'base.html' %}

{% block content %}
<br>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">capacity</th>
    </tr> 
    <tbody>
      {% for ticket in tickets %}
      
      <tr>
        {% if forloop.first %}                         
        <td>{{ ticket.travel.driver_car }}</td>
        <td>{{ ticket.travel.get_capacity }}</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </thead>

</table>

    
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Username</th>
        <th scope="col">travel</th>
        
      </tr>
    </thead>
    <tbody>
        {% for ticket in tickets %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ ticket.user }}</td>
        <td>{{ ticket.travel }}--{{ ticket.travel.get_jalali_start_time }}</td>
        
      </tr>
        {% endfor %}
    </tbody>
</table>
    <br>
{% endblock %}

travels/templates/travels/ticket_list_user.html
{% extends 'base.html' %}


{% block content %} <br>
<div style="display: flex; gap: 16px; flex-wrap: wrap;">     

    {% for ticket in tickets %}
        {% if ticket.is_available %}
            <div style="height: 100px; width: 350px; border-style: solid ;border-color: rgb(14 165 233); background-color: rgb(255, 255, 255); border-radius: 10px ; display: flex; justify-content: center; align-items: center; box-shadow: 20px 25px 11px -3px rgba(38, 91, 165, 0.1);">
                <a href="{% url 'orders:ticket_lsit_user' ticket.id %}" style="color: black;"
                >{{ ticket }} <br>{{ ticket.travel.get_jalali_start_time}}</a> <br><br>
            </div>
        {% else %}
            <div style="height: 100px; width: 350px; border-style: solid ;border-color: rgb(252, 30, 67); background-color: rgb(255, 255, 255); border-radius: 10px ; display: flex; justify-content: center; align-items: center; box-shadow: 20px 25px 11px -3px rgba(38, 91, 165, 0.1);">
                <a href="{% url 'orders:ticket_lsit_user' ticket.id %}" style="color: black;"
                >{{ ticket }} <br>{{ ticket.travel.get_jalali_start_time}}</a> <br><br>
            </div>
        {% endif %}
  
    {% endfor %}
</div>

{% endblock %}

travels/templates/travels/travel_admin_register.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}


{% block content %}
<h4>Travel Register:</h4> <br>
<div style="display: flex; margin-left: 100px;">
    <form action="" method="post">
        {% csrf_token %}
        {{ travel_form.as_p }}
        <input type="submit" class="btn btn-success">
    </form>

    <!-- By default, Datepicker using jQuery, you need to set your script after loading jQuery! -->
	<!-- loading directly -->
		<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
		<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
	<!-- OR -->
	<!-- loading by form (if used AdminJalaliDateWidget) -->
		{{ form.media }}
</div> 
{% endblock %}

travels/templates/travels/travel_list.html
{% extends 'base.html' %}

{% block content %}
  
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Driver_Car</th>
        <th scope="col">startcity</th>
        <th scope="col">destanition</th>
        <th scope="col">price</th>
        <th scope="col">distance</th>
        <th scope="col">start-time</th>
        <th scope="col">end-time</th>
        <th scope="col">date</th>
        <th scope="col">Approve</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for travel in travels %}
      
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ travel.driver_car }}</td>
        <td>{{ travel.startcity }}</td>
        <td>{{ travel.destanition }}</td>
        <td>{{ travel.get_cost }}</td>
        <td>{{ travel.get_distance }}.Km</td>
        <td>{{ travel.date_time.time }}</td>

        <td>{{ travel.end_time.time }} Date: {{ travel.end_time.date|date:"D-d-m-Y" }}</td>

        <td>{{ travel.date_time.date }}</td>
        {% if travel.approved == False %}
          <td><a href="{% url 'travels:approve_travel' travel.id %}" class="btn btn-success">Accept</a></td>
        {% else %}
          <td>Approved</td>
        {% endif %}
        <td><a href="{% url 'travels:delete_travel' %}?travel_id={{ travel.id }}" class="btn btn-danger">Remove</a></td>
      </tr>
      {% endfor %}
   
    </tbody>
</table>
    <br>
    <a href="{% url 'travels:travel_admin' %}" class="btn btn-info col-md-1">Register Travel</a>
 
{% endblock %}

travels/templates/travels/travel_list_admin.html
{% extends 'base.html' %}

{% block content %}
  
<table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Driver_Car</th>
        <th scope="col">startcity</th>
        <th scope="col">destanition</th>
        <th scope="col">price</th>
        <th scope="col">distance</th>
        <th scope="col">start-time</th>
        <th scope="col">end-time</th>
        <th scope="col">Approve</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for travel in travels %}
      
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ travel.driver_car }}</td>
        <td>{{ travel.startcity }}</td>
        <td>{{ travel.destanition }}</td>
        <td>{{ travel.get_cost }}</td>
        <td>{{ travel.get_distance }}.Km</td>
        <td>{{ travel.get_jalali_start_time }}</td>

        <td>{{ travel.get_jalali_end_time }}</td>

        {% if travel.approved == False %}
          <td><a href="{% url 'travels:approve_travel' travel.id %}" class="btn btn-success">Accept</a></td>
        {% else %}
          <td>Approved</td>
        {% endif %}
        <td><a href="{% url 'travels:delete_travel' %}?travel_id={{ travel.id }}" class="btn btn-danger">Remove</a></td>
      </tr>
      {% endfor %}
   
    </tbody>
</table>
    <br>
    <a href="{% url 'travels:travel_admin' %}" class="btn btn-info col-md-1">Register Travel</a>
 
{% endblock %}

travels/templates/travels/travel_list_to_ticket.html
{% extends 'base.html' %}

{% block content %}
<br>
<h4> Ticket List: </h4> <br>
<div style="display: flex; gap: 16px; flex-wrap: wrap;">     
    {% for travel in travels %}
    <div style="height: 100px; width: 350px; border-style: solid ;border-color: rgb(14 165 233); background-color: rgb(255, 255, 255); border-radius: 10px ; display: flex; justify-content: center; align-items: center; box-shadow: 20px 25px 11px -3px rgba(38, 91, 165, 0.1);">
        <a href="{% url 'travels:ticket_list'  travel.id %}" style="color: black;">{{ travel }} <br>{{ travel.get_jalali_start_time }}</a> <br> <br>
    </div>
        
    {% endfor %}
</div> 
{% endblock %}