accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('driver/register/<int:user_id>/', views.DriverRegisterView.as_view(), name='driver_register'),
    path('driver/travel/<int:user_id>/', views.TravelDriverInfo.as_view(), name='driver_travel'),
    path('driver/profile/<int:driver_id>/', views.DriverProfileView.as_view(), name='driver_profile'),
]
   
 
   

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homep.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('management/', include('management.urls', namespace='management')),
    path('travels/', include('travels.urls', namespace='travels')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    
]

homep/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

management/urls.py
from django.urls import path
from . import views

app_name = 'app_name'
urlpatterns = [
    path('admin/panel', views.AdminPanelView.as_view(), name='admin_panel'),
    path('admin/change/city', views.ChangeCityView.as_view(), name='change_city'),
    path('list_city/', views.ListCityView.as_view(), name='list_city'),
    path('driver/detail/', views.DriverDetailView.as_view(), name='driver_detail'),
    path('driver/panel', views.DriverRegisterAdminView.as_view(), name='driver_register_admin'),
    path('base/time/', views.BaseTimeView.as_view(), name='base_time'),
    path('base/price/', views.BasePriceView.as_view(), name='base_price'),
    path('price/list/', views.BasePriceList.as_view(), name='price_list'),
    path('car/register/', views.CarRegisterView.as_view(), name='car_register'),
    path('car/list/', views.CarListView.as_view(), name='car_list'),
    path('delete/city/', views.DeleteCityView.as_view(), name='delete_city'),
    path('driver/delete/', views.DeleteDriverView.as_view(), name='driver_delete'),
    path('submit/basepercent/', views.BasePercentView.as_view(), name='base_percent'),
    path('base/refund/', views.BaseTimeRefundView.as_view(), name='base_time_refund'),
    path('base/time/refund/list', views.BaseTimeRefundList.as_view(), name='base_time_refund_list'),
    path('base/percent/list/', views.BasePercentListView.as_view(), name='base_percent_list'),
    
    
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('add/orders/<int:travel_id>/', views.AddOrderView.as_view(), name='add_order'),
    path('orders/detail/<int:user_id>/', views.CartListView.as_view(), name='cart_list'),
    path('order/delete/', views.CartDeleteView.as_view(), name='order_delete'),
    path('ticket/detail/<int:ticket_id>/', views.TicketListUserView.as_view(), name='ticket_lsit_user'),
    path('order/pay/<int:user_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('purchased/list<int:user_id>/', views.PurchasedListView.as_view(), name='purchased_list'),
    path('purchase/delete/', views.PurchasedDeleteView.as_view(), name='purchase_delete'),
]

wallet/urls.py
from django.urls import path
from . import views

app_name = 'wallet'
urlpatterns = [
    path('wallet/add/amount/', views.AddAmountWalletView.as_view(), name='add_amount'),
    path('transection/list/', views.TransecitonListView.as_view(), name='transection_list'),
    path('transection/request/<int:transection_id>/', views.TransectionRequestListView.as_view(), name='transection_request'),
    path('user/transection/<int:user_id>/', views.TransectionLogListView.as_view(), name='user_transection'),
    path('wallet/balance/', views.WalletBalanceListView.as_view(), name='wallet_balance'),
    
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}"> {{ msg }}</p>
        {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3a9dde;box-shadow: 10px 6px 20px 11px #3498db;">
    <div class="container-fluid" style="width: 100%; ">
        <div class="container" style="display: flex; align-items: center; padding: 0; margin: 0; width: 100%; color: aliceblue; " > 
            {% if request.user.is_authenticated and user.is_superuser %}
              <a class="navbar-brand" href="{% url 'management:admin_panel' %}" style="color: white;">admin</a>
            {% elif request.user.is_authenticated and user.user_type == '2' %}
                <a class="navbar-brand" href="{% url 'accounts:driver_travel' user.id %}" style="color: white;">Driver panel</a>
            {% else %}
              <a class="navbar-brand" href="{% url 'home:home' %}" style="color: white;">Home</a>
            {% endif %}

            {% if request.user.is_authenticated %}
              <a class="navbar-brand" href="{% url 'accounts:user_logout' %}" style="color: white;">Logout</a>
            {% else %}
              <a class="navbar-brand" href="{% url 'accounts:user_register' %}" style="color: white;">Register</a>
              <a class="navbar-brand" href="{% url 'accounts:user_login' %}" style="color: white;">Login</a>
            {% endif %}

            {% if request.user.is_authenticated and user.user_type == '1' %}
                <a class="navbar-brand" href="{% url 'accounts:driver_register' user.id %}" style="color: white;">Drivers register</a>
                <a class="navbar-brand" href="{% url 'orders:cart_list' user.id %}" style="color: white;">Cart</a>
            {% elif request.user.is_authenticated and user.user_type == '2' %}
                <a class="navbar-brand" href="{% url 'accounts:driver_profile' user.id %}" style="color: white;">Driver Profile</a>
            {% endif %}
          </div>
            <div style="margin: 0; padding: 0;">
              {% if request.user.is_authenticated and user.user_type == '1' %}
              <a class="navbar-brand" style="margin: 0; padding: 0; color: white;" href="{% url 'wallet:wallet_balance' %}">Wallet/ {{ user.user_wallet.balance }}.Toman</a>
              {% endif %}
            </div>
          </div>
    </div>
</nav>